services:  
  postgres:
    image: postgres:15
    container_name: workflow-db
    env_file:
      - .env.development.container
    environment:
      POSTGRES_USER: ${WORKFLOW_DB_USER}
      POSTGRES_PASSWORD: ${WORKFLOW_DB_PASSWORD}
      POSTGRES_DB: ${WORKFLOW_DB_NAME}
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: crms-controller-redis
    ports:
      - "6379:6379"
    env_file:
      - .env.development.container
    volumes:
      - redis-data:/data

  node:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: crms-controller-app
      ports:
        - "3000:3000"
      working_dir: /usr/src/app
      command: npm run start
      env_file:
        - .env.development.container
      depends_on:
        - postgres
        - redis

volumes:
  postgres-data:
  redis-data: