name: Release CRMS Controller Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: read # Changed from write to read as checkout only needs read

jobs:
  build_and_push:
    name: 'Build and Push CRMS Controller Image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/crms-controller-app # Use github.repository which includes owner/repo

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # Added multi-platform build
          cache-from: type=gha
          cache-to: type=gha,mode=max 
